[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[phases.start]
cmds = [
  "cd backend && npm start"
]
